name: Racket CI

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        racket-version: [ 'current' ]
        racket-variant: [ 'CS', 'BC' ]
    name: Racket ${{ matrix.racket-version }} ${{ matrix.racket-variant }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: 'x64'
          version: ${{ matrix.racket-version }}
          variant: ${{ matrix.racket-variant }}
      - name: Run Tests
        run: make test
